const oneNoCategoryDrink = {
  drinks: [
    {
      idDrink: '12764',
      strDrink: 'Karsk',
      strDrinkAlternate: null,
      strDrinkES: null,
      strDrinkDE: null,
      strDrinkFR: null,
      'strDrinkZH-HANS': null,
      'strDrinkZH-HANT': null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball glass',
      strInstructions: 'Put a copper coin in a coffe-cup and fill up with coffee until you no longer see the coin, then add alcohol until you see the coin. Norwegian speciality.',
      strInstructionsES: null,
      strInstructionsDE: 'Legen Sie eine Kupfermünze in eine Kaffeetasse und füllen Sie sie mit Kaffee, bis Sie die Münze nicht mehr sehen, dann fügen Sie Alkohol hinzu, bis Sie die Münze wieder sehen. Norwegische Spezialität.',
      strInstructionsFR: null,
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/808mxk1487602471.jpg',
      strIngredient1: 'Coffee',
      strIngredient2: 'Grain alcohol',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 part ',
      strMeasure2: '2 parts ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-02-20 14:54:31',
    },
  ],
};

export default oneNoCategoryDrink;
